In [3]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.arange(2, 10)
c = np.linspace(0, 1, 10)
d = np.zeros((3, 5))
e = np.diag([1, 2, 3])
f = np.identity(3)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)


[1 2 3 4]
[2 3 4 5 6 7 8 9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
